### ISSUE TITLE
Enhance `user` string representation

### ISSUE THREAD

**Issue by lebaudantoine** [numerique-gouv/people#106]
## Feature Request

**Is your feature request related to a problem or unsupported use case? Please describe.**

For now, on `User` model, the `__str__` returns user's contact email first. It's actually something we don't use for now.

```
    def __str__(self):
        return (
            str(self.profile_contact)
            if self.profile_contact
            else self.email or str(self.id)
        )
```

**Describe the solution you'd like**
I would prefer that the string representation of the user mentions her main identity information (email and full name). It might make debugging easier.

**Comment by jblagadec** [comment]
Hello
Can this ticket be moved to En Prod? (no testing for me)
