### ISSUE TITLE
Make lint - Docker compose 

### ISSUE THREAD

**Issue by lebaudantoine** [numerique-gouv/people#108]
## Bug Report

**Problematic behavior**
⚠️ nit-picking issue

Running `make lint` command runs `app-dev` container and its dependencies:

```
(base) ➜  people git:(al-enhance-search) make lint
lint:ruff-format started…
[+] Creating 3/0
 ✔ Container people-postgresql-1   Created                                                 0.0s 
 ✔ Container people-redis-1        Created                                                 0.0s 
 ✔ Container people-mailcatcher-1  Created                                                 0.0s 
[+] Running 3/3
 ✔ Container people-mailcatcher-1  Started                                                 0.9s 
 ✔ Container people-postgresql-1   Started                                                 0.9s 
 ✔ Container people-redis-1        Started 

```
However, at the end of the lint run, the `app-dev` container is the only one to be stopped. The 3 following containers are still running:

- mailcatcher
- redis 
- postgresql

**Expected behavior/code**
I would like `app-dev` container to be stopped along with its dependencies when the `make` command stops.

**Comment by lebaudantoine** [comment]
Related to this issue, @rouja gave us the feedback that celery was buggy when running compose:
```
celery-1           | [2024-03-12 08:46:00,989: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
celery-1           | Trying again in 32.00 seconds... (16/100)
```

**Comment by Morendil** [comment]
I found [this issue](https://stackoverflow.com/questions/77267494/docker-compose-do-not-exit-depends-on-containers-on-exit-why) - the replies suggest that Docker isn't designed for this kind of use case (temporary coordinated execution with both spinning up and spinning down of dependent containers).

A possible solution that comes to mind is forcibly shutting down the ancillary containers on command completion - but that might cause more problems than it solves, e.g. if you're running `make lint` at a point in your development and checking cycle where you still need them running.

Unless I'm missing something, leaving the containers running doesn't seem like it would cause trouble in and of itself ? I would be inclined to close the issue (as "won't fix") but please comment if there are consequences I'm not aware of.
