### ISSUE TITLE
Fix DropButton interaction

### ISSUE THREAD

**Issue by lebaudantoine** [numerique-gouv/people#110]
## Bug Report

**Problematic behavior**
I cannot close `DropButton` when it's opened.

https://github.com/numerique-gouv/people/assets/45729124/1807812c-37e4-45e3-ada0-86d11b72646a

**Expected behavior/code**

I would like to be able to close the `DropButton` by clicking :
- Again on the button
- Outside the menu

Please find an example of the desired behavior:

https://github.com/numerique-gouv/people/assets/45729124/5e1e2245-bec7-4150-a022-35f199fd5db1

**Comment by lebaudantoine** [comment]
nit: the small arrow shape is missing 
<img width="1296" alt="Capture d’écran 2024-03-13 à 09 23 27" src="https://github.com/numerique-gouv/people/assets/45729124/67e67630-a5b1-4345-8e0c-9e658c040973">

**Comment by AntoLC** [comment]
> nit: the small arrow shape is missing <img alt="Capture d’écran 2024-03-13 à 09 23 27" width="1296" src="https://private-user-images.githubusercontent.com/45729124/312370299-67e67630-a5b1-4345-8e0c-9e658c040973.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzNDI1MzgsIm5iZiI6MTcxMDM0MjIzOCwicGF0aCI6Ii80NTcyOTEyNC8zMTIzNzAyOTktNjdlNjc2MzAtYTViMS00MzQ1LThlMGMtOWU2NThjMDQwOTczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDE1MDM1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0NTQ2Nzc4NzNjZDMwYzhkM2Y2ZTFmOTU0YzY5ZTcxYTNlMzVlOWIyZWNhNTVjMDI5MDZiYWMxMDc3MGVmMGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.D5QrNfZbBx61q9Jjw-Bx9Tpdr483F2u3zfLGbiT373I">

This component (DropButton) will probable disappear soon, better to not spend too much time on it, let's request this feature in Cunningham if we really want it.

**Comment by lebaudantoine** [comment]
Agree let's ignore it !
