### ISSUE TITLE
✨(app-frontend) feature to remove a member from a team

### ISSUE THREAD

**Issue by AntoLC** [numerique-gouv/people#121]
## Feature Request

- Integrate endpoint to remove user
- Integrate new design
 ---
- ⚠️ Be sure that the design is validated with the team before starting this dev (Johann / Antoine / Anto / JB ?).

- ⚠️The bulk editing use a datagrid, so it can be smart to use more or less the same components that we use for the bulk editing.

![image](https://github.com/numerique-gouv/people/assets/25994652/a38644bb-0fab-4d80-b1eb-9759e0a66aa4)

**Comment by lebaudantoine** [comment]
Endpoint is ready! Design is validated, we can go for dev!
