### ISSUE TITLE
✨(app-desk) update team name

### ISSUE THREAD

**Issue by AntoLC** [numerique-gouv/people#122]
## Feature Request

Update the team name.

 ---
- ⚠️ Be sure that the design is validated with the team before starting this dev (Johann / Antoine / Anto / JB ?).

- ⚠️We already have a design made with all the logic integrated when we create a team, see how we can reuse that (see more with Johann) 

![image](https://github.com/numerique-gouv/people/assets/25994652/50f74a25-42fb-4ff3-805b-fd76a0af2587)
![image](https://github.com/numerique-gouv/people/assets/25994652/6c29db3a-3af6-4cc0-a313-b7feae3330bb)

**Comment by lebaudantoine** [comment]
<img width="810" alt="Capture d’écran 2024-03-18 à 23 08 53" src="https://github.com/numerique-gouv/people/assets/45729124/19b76812-89e6-482c-bfe0-6486a2c7ce5c">

**Comment by lebaudantoine** [comment]
design is ready !
