### ISSUE TITLE
✨(app-desk) closing team panel

### ISSUE THREAD

**Issue by AntoLC** [numerique-gouv/people#124]
## Feature Request

Make the team panel closable.

⚠️ Be sure that the design is validated with the team before starting this dev (Johann / Antoine / Anto / JB ?).

![image](https://github.com/numerique-gouv/people/assets/25994652/b172fadc-fff2-4ff3-9e98-57bd87e33634)

**Comment by lebaudantoine** [comment]
I have reviewed the design with Johan, He tagged you on the design file. It's now ready for dev.

**Comment by lebaudantoine** [comment]
Please note that Johann decided to change the add icon from round to square
