### ISSUE TITLE
🐛(CI) job i18n-crowdin don't push to crowdin

### ISSUE THREAD

**Issue by AntoLC** [numerique-gouv/people#129]
## Bug Report

The `i18n-crowdin` job doesn't push automatically anymore the new translation to crowdin.

https://github.com/numerique-gouv/people/blob/f503120b3c4dd569847a5815a1148c48217f8e71/.github/workflows/people.yml#L249-L252

**Comment by lebaudantoine** [comment]
I got a segmentation fault when running `make i18n-generate-and-upload`

**Comment by Morendil** [comment]
Looking into this, I found
- the job was removed in #319 
- running the target manually works properly

Closing as resolved, might want to reopen if that segfault reoccurs.
