### ISSUE TITLE
[Desk] Modifications de textes

### ISSUE THREAD

**Issue by jblagadec** [numerique-gouv/people#222]
**Bouton pour ajouter un membre à un groupe**
- [ ] Anglais : remplacer "Add" par "Add a member"
- [ ] Français : remplacer "Ajouter" par "Ajouter un membre"

**Titre du menu des groupes**
- [ ] Anglais : Remplacer "Recents" par "Groups"
- [ ] Français : Remplacer "Récents" par "Groupes"

**Titre de la page de création de groupe**
- [ ] Anglais : Remplacer "Name the team" par "Create a new group"
- [ ] Français : Remplacer "Nommer le groupe" par "Créer un nouveau groupe"

**Modale pour retirer un membre d'un groupe**
- [ ] Anglais : Remplacer "Remove the member" par "Remove this member from the group"
- [ ] Français : Remplacer "Supprimer le membre" par "Retirer ce membre du groupe"
- [ ] Supprimer l'icône qui n'est pas pertinente

**Comment by daproclaima** [comment]
@jblagadec, "Supprimer l'icône qui n'est pas pertinente", c'est cette icône en screenshot qui n'est pas pertinente?

![Image](https://github.com/numerique-gouv/people/assets/33085077/3947f2ce-b0ef-4ecc-a886-979c900a1bec)

**Comment by jblagadec** [comment]
Absolument ! 
On s'était dit au moment de l'audit que ça laissait entendre qu'on supprime un groupe, alors qu'on veut juste supprimer un membre
