### ISSUE TITLE
[Desk] Modif du bloc-marque dans le header

### ISSUE THREAD

**Issue by jblagadec** [numerique-gouv/people#223]
Dans le header et dans le footer, pour l'instant le bloc-marque indique "Intitulé" ;)

=> Remplacer par "République Française"

Si besoin, je joins des svg du bloc marque en différentes versions
- avec ou sans Marianne
- avec ou sans marges
en fonction de ce qui est nécessaire pour se rapprocher le plus possible de l'aspect visuel du header et du footer du DSFR

![Bloc marque République Française - avec Marianne - sans marge](https://github.com/numerique-gouv/people/assets/121045817/f3d32605-a969-4191-ae06-7eb32d23a414)
![Bloc marque République Française - sans Marianne - sans marge](https://github.com/numerique-gouv/people/assets/121045817/03e761b5-8ff3-45e1-a7fe-db06ddab5991)
![Bloc marque République Française - sans Marianne - avec marges](https://github.com/numerique-gouv/people/assets/121045817/e11b8e46-74d9-4af8-b1d0-b9ae95a3740c)
![Bloc marque République Française - avec Marianne - avec marges](https://github.com/numerique-gouv/people/assets/121045817/38c05e4f-4f39-452a-955b-7d4363939982)

**Comment by AntoLC** [comment]
Here the refacto on Impress side: 
https://github.com/numerique-gouv/impress/commit/6e46b686abc674b87042429c02a1fb3030e1a9da
