### ISSUE TITLE
[Régie] Allow authenticated users to see the list of mail domains

### ISSUE THREAD

**Issue by daproclaima** [numerique-gouv/people#226]

**Comment by jblagadec** [comment]
On est d'accord que sur ce ticket, la règle adoptée est que n'importe quel user qui est rattaché à un domaine peut le voir dans sa liste, quel que soit le rôle du user et quel que soit le statut du domaine ?
(je demande pour m'assurer que je vérifie bien le bon comportement du produit lors de ma recette)
