### ISSUE TITLE
Restreindre les droits pour la création de boite mail

### ISSUE THREAD

**Issue by sdemagny** [numerique-gouv/people#231]

**Comment by mjeammet** [comment]
@sdemagny ça c'est bon, non ?

**Comment by Morendil** [comment]
@sdemagny @mjeammet @jblagadec Je fais un peu de ménage dans les issues qui sont marquées "déployées en prod". Si vous avez un doute en voyant la notif, faites un noeud à votre mouchoir pour en parler jeudi ;)
