### ISSUE TITLE
🐛Cannot access mail domain with id

### ISSUE THREAD

**Issue by AntoLC** [numerique-gouv/people#252]
## Bug Report

A recent commit changed the way we access to a maill domain: https://github.com/numerique-gouv/people/commit/b4bafb6efbcfae4ed8a116061ee471a27737c41e

![image](https://github.com/numerique-gouv/people/assets/25994652/ae71f49c-ba98-4298-9f58-93e645a18e3b)

## What to do
To access to a mail domain, we need to use now the `slug` and not the `id`.

https://github.com/numerique-gouv/people/blob/35a897fa60ef84d5cef54e63651a1fe649cd3592/src/frontend/apps/desk/src/pages/mail-domains/%5Bid%5D.tsx#L28

**Comment by daproclaima** [comment]
This issue is related to the PR #228. PR 228 was just merged into main branch before adapting the frontend. This issue #252 adapts the frontend.
