### ISSUE TITLE
Intégrer une page "Mentions légales" et "Cookies", accessibles depuis le footer

### ISSUE THREAD

**Issue by jblagadec** [numerique-gouv/people#264]

**Comment by AntoLC** [comment]
Dans cette PR (https://github.com/numerique-gouv/people/pull/207) j'ai mis les mentions légales, je pense que c'est correct, c'est Sam qui m'a passé ca la semaine dernière.

**Comment by jblagadec** [comment]
Hello @AntoLC ah je n'avais pas vu, merci pour l'info !

Dans la version actuelle du texte, il y a juste un détail qui m'étonne
Dans les mentions légales, dans la section **Plus d'infos**, on ne parle que de la Suite Numérique, et on donne l'adresse de contact lasuite@modernisation.gouv.fr.
Or je me dis que pour les utilisateurs qui utilisent la Régie dans le cadre de La Suite Territoriale, il faut aussi mentionner la Suite Territoriale et donner l'adresse de contact suiteterritoriale@anct.gouv.fr... non ? 
Est-ce que tu penses que ça vaut le coup d'ouvrir cette question auprès de Samuel / Thibaud ?

**Comment by jblagadec** [comment]
Dernière remarque : peut-on écrire "Mentions légales" au pluriel dans le footer, plutôt que "Mention Légale" ?
J'ai l'impression que c'est plutôt l'usage courant

**Comment by jblagadec** [comment]
=> Suite à la réponse de Samuel : le texte peut rester tel quel pour l'instant ;)

Il y a donc juste à remplacer "Mention Légale" par "Mentions légales"
