### ISSUE TITLE
Section Messagerie : remplacer le texte en cas de page vide

### ISSUE THREAD

**Issue by jblagadec** [numerique-gouv/people#276]
Pour l'instant, s'il n'existe aucune boite liée à un nom de domaine, on voit le message "This table is empty"
avec un visuel de tableau

=> A remplacer par une phrase plus explicite pour l'utilisateur

FR : Aucune boîte mail n'a été créée avec ce nom de domaine.
EN : No mail box was created with this mail domain.

Visuel à supprimer

**Comment by daproclaima** [comment]
https://openfun.github.io/cunningham/storybook/?path=/story/components-datagrid--empty-custom-no-image

**Comment by jblagadec** [comment]
Recette OK
