### ISSUE TITLE
Accessibilité : corriger la navigation au clavier (tabulation et focus)

### ISSUE THREAD

**Issue by jblagadec** [numerique-gouv/people#282]
On rencontre plusieurs problèmes dans la navigation au clavier. Je les décris rapidement ci-dessous, mais je peux évidemment faire un point de synchro avec la personne qui prendra ce ticket, pour tester en live et se mettre d'accord sur les comportements attendus :)

**Problèmes constatés :**
- le focus n'est pas visible sur le bouton "Mon compte"
- il y a un double focus sur certains éléments (sur le dropdown de changement de langue, sur le CTA "Créer un nouveau groupe", sur le bouton "Annuler" du formulaire de création de groupe...)
- il y a des focus "invisibles" entre chaque éléments du menu vertical de gauche (... et plusieurs aussi par la suite)
- les CTA deviennent illisibles lorsqu'ils prennent le focus clavier (par exemple pour "Créer un boîte mail") : contraste entre le texte et son arrière-plan égal à 1:1)
- d'une manière générale, il y a manque de consistence dans l'aspect visuel du focus

**Correctifs**
- Le focus doit être visible sur tous les éléments interactifs
- On ne doit pas avoir de double focus sur un même élément
- On doit supprimer les focus invisibles
- Avec le focus, les CTA doivent toujours respecter cette règle : le contraste entre le texte et son arrière-plan doit être d'au moins 4,5:1. On peut par exemple passer le texte en blanc pur
- Le focus doit toujours avoir le même aspect, et être suffisamment contrasté par rapport à son arrière-plan (au moins 3:1). Si besoin, garder le paramétrage automatique du navigateur pour gérer cet aspect.

**Comment by daproclaima** [comment]
Le mieux pour ces deux éléments est de contribuer directement au code de cunningham (composants Modal et Select).

J'ai appliqué un fix temporaire pour le selecteur de langue. Par contre, je ne parviens pas à régler le souci sur les Modales depuis le code de la Régie.

**Comment by daproclaima** [comment]
Fix temporaire appliqué aussi sur le composant Modal.

**Comment by jblagadec** [comment]
Top merci @daproclaima 
Recette OK en staging pour les 2 points.

En revanche je ne fais pas les mêmes constats en préprod... est-ce normal ?
