### ISSUE TITLE
Nom de groupe déjà existant : modifier le message d'erreur

### ISSUE THREAD

**Issue by jblagadec** [numerique-gouv/people#293]
![Image](https://github.com/user-attachments/assets/fa902368-f8f4-4298-a533-9ca77720421a)

Modifications : 

1) Comme la notion de "Slug" ne parle pas aux utilisateurs, il faut remplacer cette phrase pour qu'elle soit explicite : 
- FR : "Un autre groupe utilise déjà ce nom. Veuillez en saisir un autre."
- EN : "This name is already used for another group. Please enter another one." 

2) Comme pour les autres formulaires, il faut que cette erreur soit liée directement au champ auquel elle fait référence.
=> Utiliser le message d'erreur inclus dans le composant initial pour afficher cette erreur.

3) **[MODIF À DISCUTER]** Sur le motif lui-même de l'erreur : comment se fait-il qu'on me dise que ce Slug existe déjà, alors que je ne le vois pas dans l'interface ?
- Est-ce parce qu'il a existé puis a été supprimé ?
 -Est-ce parce qu'un autre utilisateur l'a créé dans un autre groupe, auquel je n'ai pas accès ?
Dans les 2 cas, je pense qu'il faudrait que ce slug/nom soit à nouveau utilisable...

**Comment by Morendil** [comment]
Apparemment il y a une régression sur cette évolution ? En local sur main, ou sur staging, c'est l'ancien comportement qu'on peut observer.

**Comment by qbey** [comment]
This will be "fixed" in https://github.com/numerique-gouv/people/pull/480 because we remove the slug unicity.

**Comment by jblagadec** [comment]
Recette : OK avec le fix du #480 (pas d'erreur avec un nom de groupe déjà existant)
