### ISSUE TITLE
En tant qu'utilisateur, je veux voir les prénom et nom des membres d'un groupe

### ISSUE THREAD

**Issue by jblagadec** [numerique-gouv/people#294]
![Image](https://github.com/user-attachments/assets/60233072-bb83-49db-94c1-5a6f5f0684e5)

![Image](https://github.com/user-attachments/assets/0cf9644c-7ce8-44e2-8f31-a548eec2bd87)

Pour l'instant, on n'affiche pas les prénom / nom d'un utilisateur dans un groupe.
Est-ce parce que l'appel n'est pas encore intégré ? (auquel cas il faut le faire)
ou juste parce que les utilisateurs n'ont ni prénom ni nom en BDD ?

**Comment by mjeammet** [comment]
Pour l'instant il existe un unique champ "nom". On peut le split en "prénom" et "nom" pour pouvoir ensuite trier par nom.

**Comment by daproclaima** [comment]
These are actually from 2 different features.

**Comment by jblagadec** [comment]
Je vois que ce ticket est en recette, pourtant la situation n'a pas évolué d'après ce que je vois ;)

Est-ce parce que les membres affichés dans mes screenshots ci-dessus n'ont pas de prénom/nom en BDD ?
Ou est-ce parce que le front ne les affiche pas ?
