### ISSUE TITLE
Modale pour retirer un utilisateur d'un groupe : modification de wording

### ISSUE THREAD

**Issue by jblagadec** [numerique-gouv/people#295]
Dans la modale de confirmation pour retirer un membre d'un groupe, il faut modifier les textes actuels.

cf. maquette Figma : 
https://www.figma.com/design/Qn0H9DmBjae6pD6HTjKX3i/R%C3%A9gie?node-id=1264-9980&t=WhfLXGOEWcYykC0x-4

ou les wordings ci-dessous :

**TITRE DE LA MODALE**
FR : remplacer par **Retirer le membre du groupe**
EN : OK tel quel

**LIGNE DE TEXTE**
FR : Remplacer par : "Voulez-vous vraiment retirer ce membre du groupe XXX ?"
(avec un espace avant le point d'interrogation s'il vous plaît 🤓)
EN : OK tel quel

**CTA**
FR : Remplacer par "Retirer du groupe"
EN : Remplacer par "Remove from the group"

**Comment by jblagadec** [comment]
@daproclaima 
Recette KO pour moi sur la ligne de texte : on a toujours la phrase "Êtes-vous sûr de vouloir supprimer ce membre du groupe XXX?"
et non pas "Voulez-vous vraiment retirer ce membre du groupe XXX ?"

**Comment by daproclaima** [comment]
Il faut qu'un dev approuve le changement de texte sur crowdin. J'ai prévenu Anthony LC

**Comment by daproclaima** [comment]
Les droits m'ont été accordés. Le droit d'éditions de traduction n'était pas suffisant. En fait, j'avais créé la traduction mais elle était inapplicable : une autre avait été approuvée et je n'avais pas les droits pour moi aussi pouvoir en approuver/désaprouver. C'est réglé
