### ISSUE TITLE
Admin inaccessible

### ISSUE THREAD

**Issue by lebaudantoine** [numerique-gouv/people#307]
## Bug Report

**Problematic behavior**
Asking for a sub and a password instead of the **expected** email and password (as mentioned in the Readme):
<img width="737" alt="Capture d’écran 2024-07-28 à 18 36 30" src="https://github.com/user-attachments/assets/ff501f23-57bd-4ac0-958f-44c7977d2e20">

**Expected behavior/code**
Revert and fix this regression.

**Comment by lebaudantoine** [comment]
Actually, when searching through commits' history, I've found these changes by @sampaccoud https://github.com/numerique-gouv/people/commit/2ec292bb9105486cd7183fab1aa7ba7166ddcd2e.

Passing `admin` as a `sub` allowed me to logged-in. We should definitely change input's name by `username` and keep the README up-to-date

**Comment by mjeammet** [comment]
Although very username-y, "admin" is actually the sub of the admin user.
I'll update the README.

**Comment by jblagadec** [comment]
Hello 
Can this ticket be moved to En Prod? (no testing for me)
