### ISSUE TITLE
A user can not create a mailbox for a domain if it is not enabled

### ISSUE THREAD

**Issue by daproclaima** [numerique-gouv/people#336]

**Comment by daproclaima** [comment]
I need to find a way to show elegantly the creation status on UI.

**Comment by jblagadec** [comment]
**RECETTE**

2 remarques 👍 

1) Je constate un comportement étrange sur le statut "En attente". 
Je vois plusieurs NDD ayant ce statut. Pourtant il y en a un pour lequel on voit le bouton "Créer une boîte mail" (désactivé), et l'autre pour lequel on ne voit pas ce bouton.
=> Comment ça se fait ? Est-ce un bug ?



![Image](https://github.com/user-attachments/assets/55d611b4-bdc2-4c86-8464-e27bcdf46d34)



![Image](https://github.com/user-attachments/assets/9387c67d-b842-486d-8e38-9f2cedec8899)



2) Afin de pouvoir recetter ce
