### ISSUE TITLE
Section Groupes : masquer la section en Prod, mais la garder visible en staging/préprod (pour évols et recette notamment)

### ISSUE THREAD

**Issue by jblagadec** [numerique-gouv/people#340]
Définir le feature flag dans les fichiers d'environnement

**Comment by AntoLC** [comment]
La feature "Groupe" est active en `dev` et `staging` la du coup, en `preprod` et `prod` elle est desactivée. 
`preprod` est censé etre une copie conforme de `prod` (conf / version docker), `preprod`  permet de voir à l'avance comment sera la `prod`.

**Comment by mjeammet** [comment]
Est-ce qu'on peut cloturer cette issue @AntoLC @jblagadec ?
