### ISSUE TITLE
[BUG] Impossibilité de créer une boîte mail dans un domaine actif (en staging et préprod)

### ISSUE THREAD

**Issue by jblagadec** [numerique-gouv/people#351]
Quand on remplit le formulaire correspondant, et qu'on valide, il ne se passe rien.

**Comment by daproclaima** [comment]
Je pense que les interceptions de requêtes envoyées à l'API que j'ai mis en place dans les tests e2e ont empêché de tester l'API et mettre en évidence ce comportement. Ces interceptions empêchent de vérifier complètement la création de boîte mail. 
Si un domaine de messagerie ne possède pas de secret ou si ce secret est invalide, alors on ne peut pas créer de boîte mail. Je ne connais pas la syntaxe du string pour le secret.
Je regarderai ça demain.

Lorsqu'il n'y a pas de secret du tout, l'API retourne "Please configure your domain's secret before creating any mailbox." Sur le frontend, je capture cette erreur pour que l'on affiche à la place "The mail domain secret is misconfigured. Please, contact our support to solve the issue: suiteterritoriale@anct.gouv.fr."

Lorsque le domaine possède un secret mais que c'est un secret invalide, l'API retourne une erreur 500. Je dois faire en sorte d'afficher un message pour les erreurs 500; je pense à "Votre demande ne peut pas être traitée car le serveur rencontre une erreur. Si le problème persiste, veuillez contacter le support pour résoudre le problème : suiteterritoriale@anct.gouv.fr."

Je n'ai pas accès à l'application, ni la console d'admin de la preprod (si Sabrina n'y a pas accès non plus, alors les domaines mails n'ont certainement pas de secrets de configurés et ça expliquerai l'incapacité à créer des boîtes mails)

**Comment by daproclaima** [comment]
@sdemagny, @mjeammet, modifier le test e2e de création de boîte mail en interagissant avec le back (un vrai test e2e) est complexe. Cela induit que durant les tests la BDD devrait posséder un domaine de messagerie actif et secret valide... Ou bien de piloter automatiquement la manipulation du domaine depuis l'interface Django Admin pour l'activer et compléter son secret.

Aussi, comment est-ce que l'on remplit le secret d'un nom de domaine ? C'est dimail qui doit le retourner, un hash random généré manuellement ?

**Comment by daproclaima** [comment]
Tout ce que j'ai pu faire est de capturer les erreurs retournées et afficher une cause d'erreur sur l'UI. J'ai besoin d'aide pour comprendre comment on configure le secret.
