### ISSUE TITLE
Display Régie version in footer

### ISSUE THREAD

**Issue by mjeammet** [numerique-gouv/people#369]
## Feature Request

Because it's nice and clear.

Côté back : ajouter l'info de version dans le endpoint /config/

Ajout JBL : pour le front, je propose de le rajouter de façon discrète à côté de la mention etalab, par exemple comme ceci : 

![Image](https://github.com/user-attachments/assets/af8b8e34-24ae-426d-8f43-3bc6cd4f3d6c)

**Comment by Morendil** [comment]
Do we need to add an API endpoint only for that ? I guess that we'll sometimes need to ask what version the API we are using… but if this isn't a frequent concern, just putting it in the frontend is already a win.

OTOH I don't know what the preferred way of getting the version (either commit id or release number) from Github. Do we do this as part of the build process ? Output the result of `git rev-parse --short HEAD` and concat that file to some JS ?
