### ISSUE TITLE
use slugs in URLs

### ISSUE THREAD

**Issue by mjeammet** [numerique-gouv/people#42]
## Feature Request

**Is your feature request related to a problem or unsupported use case? Please describe.**
Not a fix

**Describe the solution you'd like**
use slugs instead of uuids to reach a team page. i.e.: `teams/my-team` instead of `teams/5393482e-7ee4-45f2-a5fa-0ee4753e007f`

advantages : 
- easier to remember / type by hand for direct access

drawbacks : 
- as slugs can change, we'd have to be careful to still reference team by their ids

~~**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered.~~

~~**Discovery, Documentation, Adoption, Migration Strategy**~~

~~If you can, explain how users will be able to use this and possibly write out a version the docs (if applicable).~~
~~Maybe a screenshot or design?~~

**Do you want to work on it through a Pull Request?**
yas !

**Comment by Morendil** [comment]
This was done in #36 - and undone in #480. (Sometimes that's the price of learning!)
