### ISSUE TITLE
En tant qu'utilisateur, je veux voir mon nom dans le header dès que je suis authentifié

### ISSUE THREAD

**Issue by jblagadec** [numerique-gouv/people#421]
Pour l'instant on voit dans le header la mention "mon compte" qui amène au bouton pour se déconnecter.

On veut remplacer ça par "Prénom Nom" de l'utilisateur, comme dans l'exemple : 

![Image](https://github.com/user-attachments/assets/e0e00b97-7819-492a-ab04-d28e02eb1963)

**Comment by mjeammet** [comment]
DONE
