### ISSUE TITLE
Mauvais filtrage sur les membres d'un groupe en staging

### ISSUE THREAD

**Issue by jblagadec** [numerique-gouv/people#438]
Je n'ai pas réussi à définir une règle générale, mais je constate que certaines chaînes de caractères font apparaître des résultats non pertinents.

À re-tester pour confirmer s'il s'agit bien d'un bug, car je n'ai que peu de membres avec nom / prénom dans un groupe...

Quelques exemples rencontrés ci-dessous (globalement il s'agit de "faux positifs", et j'ai l'impression que c'est lié au début de la chaîne de caractères) : 

![Image](https://github.com/user-attachments/assets/872488b3-2bf8-4afd-9faf-50cbe44d141a)

![Image](https://github.com/user-attachments/assets/eb29576e-3bfd-4d13-b377-29a3f0c40aca)

**Comment by mjeammet** [comment]
et oui c'est moi mmdfezjfguih !

Plus sérieusement, oui, on sait que l'algo de filtrage fait des trucs bizarres (elle fait les mêmes trucs bizarres côté équipes). Il faut qu'on prenne le temps d'enquêter pour comprendre comment ça fonctionne et de configurer ça.

**Comment by Morendil** [comment]
Corrigé par #495
