### ISSUE TITLE
Pouvoir initier la création des boîtes de messagerie même sur un domaine « en attente »

### ISSUE THREAD

**Issue by jblagadec** [numerique-gouv/people#487]
But : éviter la frustration d'être bloqué dans mes actions que je viens de créer un NDD.

La proposition de cette story c’est de ne pas attendre que le domaine bascule en « actif » avant d’autoriser la création de boîtes. (Il faut peut-être ajouter un champ technique dans l’objet boîte pour signaler qu’elle est créée dans Régie mais pas encore dans Dimail, par exemple.)

Pour cette boîte mail initiée :
- afficher un statut “en attente” dans une nouvelle colonne du tableau avec en-tête "Statut"
- et un message explicatif dans un toaster, e.g. “Boîte mail créée ! L’utilisateur sera notifié de la création de sa boîte dès que le domaine sera actif."

Quand une boîte est définitivement créée, on peut lui donner le statut "active"

**Comment by jblagadec** [comment]
Implications : 

- Création d'un objet boîte mail côté Régie + statut, indépendamment de dimail
- refaire l'appel côté dimail 
- Faire des traitements asynchrones côté Régie

**Comment by mjeammet** [comment]
Les boites mails ont actuellement 4 status : pending, enabled, failed et disabled. Pour l'instant, seul "enabled" autorise la création de boites mails sur ce domaine.

J'ajoute les 3 autres ? 
Qu'est-ce qu'on avait en tête derrière "Disabled" ?

**Comment by jblagadec** [comment]
Hello @mjeammet  J'avais pas vu ce commentaire jusque là, mais je me permets de me prononcer :)

Ce qui me semble avoir le plus de sens, ce serait d'autoriser la création de boîte mail pour les statuts du NDD : 
- **enabled** (évidemment)
- **failed** (en tout cas tant qu'on estime que le cas d'erreurs tech seront généralement de courte durée => ainsi dès la résolution, les boîtes mail sont définitivement créées)
- **pending** (comme dit plus haut)

Mais PAS pour le statut **disabled** => si l'équipe Suite ou un admin de l'organisation veut désactiver un NDD, je pense que ce sera pour vraiment bloquer toute activité sur ce NDD, donc ne pas laisser penser qu'on peut encore créer des boîtes...

Qu'en dis-tu ?

**Comment by jblagadec** [comment]
Recette KO : pour un domaine en attente, même si j'ai le statut Propriétaire, je ne peux pas créer de boîte mail : le bouton concerné est inactif et le message d'erreur apparaît comme auparavant.

Par ailleurs j'ai aussi voulu tester en créant un nouveau domaine qui aurait le statut en attente, et cette fonctionnalité est down, j'ai donc créé le ticket de bug 470 
https://github.com/orgs/numerique-gouv/projects/2/views/1?pane=issue&itemId=89515899
