### ISSUE TITLE
Configure Redis to cache session

### ISSUE THREAD

**Issue by lebaudantoine** [numerique-gouv/people#66]
## Feature Request

**Is your feature request related to a problem or unsupported use case? Please describe.**
Update the backend used by the session engine, to improve system performances.

**Describe the solution you'd like**
Use Redis to handle session.

**Comment by Morendil** [comment]
This was done in #130 - per [Django docs](https://docs.djangoproject.com/en/5.1/topics/http/sessions/), having both `SESSION_ENGINE` set to `django.contrib.sessions.backends.cache` (since #59) and Redis setup in `CACHES` (in `settings.py`) means sessions are (non-persistently) cached in Redis.
